# Generated by Django 3.1.7 on 2021-03-11 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=250)),
                ('star_rating', models.FloatField(validators=[django.core.validators.MaxValueValidator])),
                ('date_of_review', models.CharField(max_length=250)),
                ('closed_with_lender', models.BooleanField()),
            ],
        ),
    ]
