# Generated by Django 3.1.7 on 2021-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210311_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='closed_with_lender',
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.CharField(max_length=250),
        ),
    ]
